### ISSUE TITLE
Credential to get access to the grafana data

### ISSUE THREAD

**Issue by supermenteur** [SvenSommer/MMM-GrafanaChart#1]
I'm wondering how you manage the credential to access Grafana.
Without credential, I'm reaching the login page.

Thanks.

**Comment by SvenSommer** [comment]
Enable authentication in the [http] section of the configuration file /etc/influxdb/influxdb.conf:
`[http]
enabled = true bind-address = ":8086" # change to a specific interface if needed 
auth-enabled = true # will enforce authentication`

everything is described in the tutorial on http://robstechlog.com/2017/06/30/personal-weather-chart-module/
