### ISSUE TITLE
Cannot adjust height in %

### ISSUE THREAD

**Issue by drtorchwood** [SvenSommer/MMM-GrafanaChart#13]
Hi, 

setting the width and height in px works fine. However, if I use % to give a size, it only works for width but not for height. I can set `height: "300%"` or `height: "20%"` but the height never changes. 

Is this an GrafanaChart problem, a grafana problem or something else?

**Comment by klaernie** [comment]
This is to be expected, since every module in MagicMirror is inside a absolutely positioned region `div`.
