### ISSUE TITLE
No function anymore?

### ISSUE THREAD

**Issue by Bluefish67** [SvenSommer/MMM-GrafanaChart#14]
Hello, it looks like it does not work now.

No changes were made to the configuration but the display under MagicMirror then shows the following:
- this could be caused by your reverse proxy settinngs
- if you host grafana under subpath make sure your grafana.ini root_url setting includes subpath
- if you have a local dev build make sure your build frontend using yarn start:hot or yarn build 
- sometimes restarting grafana-server can help

I can't do anything with the error message since I don't use or have used a reverse proxy.

The version of Grafana is v8.4.2

**Comment by klaernie** [comment]
Did you try accessing grafana from the same machine and same URL as you have configured? Could you share your config?

**Comment by klaernie** [comment]
no response, closing the issue
