### ISSUE TITLE
Is it possible to set the background color of the frame in Magic Mirror?

### ISSUE THREAD

**Issue by danielXengines** [SvenSommer/MMM-GrafanaChart#17]
Observed behaviour : Background color of the Grafana module is not completely black and the frame does not appear to be flushed with the rest of the screen

Expected behaviour  : The grafana frame in magic mirror has a black background

Currents displaying a panel with temperatures, using "Stat"
Base color is set to RGBA(0,0,0,0)
Tried both options background transparent enabled and disabled. In Grafana, the frame appears completely black. However, on the magic mirror it is slightly gray. The border of the entire frame is visible. For some reason it looks more prominent on the magic mirror than on the screen shot attached.

Any suggestions welcome! Thank you.

![image](https://user-images.githubusercontent.com/45204368/209967055-29107d04-23c6-4162-815e-47e4a30ecdb9.png)

**Comment by monty124** [comment]
I'd also like to know if this is possible too

**Comment by klaernie** [comment]
@danielXengines, @monty124 : Did you configure the grafana panel to have a transparent background?
![image](https://user-images.githubusercontent.com/5636383/231817130-fd3022c5-1c2d-4d7e-9f1c-5a96065f8d85.png)
Sadly also the grafana docs only mention it in one screenshot: https://grafana.com/docs/grafana/latest/panels-visualizations/configure-panel-options/

**Comment by monty124** [comment]
yep I saw this in the settings and have set it, it does not seem to be transparent; you can still see the outline but i've come to terms with it lol.
I think its something to do with the underlying browser and how it renders tbh

**Comment by klaernie** [comment]
Anyway, you should be able to set everything outside the iframe using custom css, but inside the iframe is probably prohibited by the cross-origin policies.
