### ISSUE TITLE
takes me to login page

### ISSUE THREAD

**Issue by icripps** [SvenSommer/MMM-GrafanaChart#4]
its takes me to login page, after logging in, it rquests for the credentials again

**Comment by GitPetri** [comment]
I got rid of Grafana logins by modifying grafana.ini on the grafana host:


[auth.anonymous]
# enable anonymous access
;enabled = false
**enabled = true**

# specify role for unauthenticated users
;org_role = Viewer
**org_role = Viewer**

**Comment by SvenSommer** [comment]
Thanks for sharing. I will try it out tomorrow!
Have a nice day!

**Comment by SvenSommer** [comment]
Necessary changes in the grafana.ini are now described in the readme.md described
