### ISSUE TITLE
refused to connect with Grafana v6.5.2

### ISSUE THREAD

**Issue by TokTias** [SvenSommer/MMM-GrafanaChart#5]
Hi !
I just updated my Grafana to v6.5.2 and since then the MMM-GrafanaChart refuses to connect.
The Grafana log clearly shows that it accepts the connection with status=200 and if I enter the URL manually based on how it's constructed in the MMM-GrafanChart.js file in my browser, I get the charts shown as a full page. So the URL is correct and Grafana accepts and responds to it.

Is there something new I need to configure in Grafana (or for MMM-GrafanaChart) to make it work with v6.5.2 ?

Cheers !
/T

**Comment by CMALG** [comment]
@TokTias i have created a pull request to make it usable with 6.x
did you set these options in the grafana.ini ?
[auth.anonymous]
# enable anonymous access
enabled = true

# specify organization name that should be used for unauthenticated users
org_name = Main Org.

# specify role for unauthenticated users
org_role = Viewer

[security]
allow_embedding = true

**Comment by TokTias** [comment]
Hi !
many thanks for your reply. Adding this setting and restarting the grafana-server fixed it :

[security]
allow_embedding = true

Cheers !
/T

**Comment by SvenSommer** [comment]
Thanks for reporting and fixing. Pull request is merged, readme.md is updated with grafana settings.
