### ISSUE TITLE
Scrolling issue

### ISSUE THREAD

**Issue by evroom** [SvenSommer/MMM-GrafanaChart#8]
Hi,

I have `position: 'fullscreen_above',` but I do not see the complete dashboard.
I can scroll the dashboard up and down, but I would like to see the complete dashboard on my MM display.

Is this a Grafana issue, or a MMM-GrafanaChart issue ?

<img width="797" alt="Grafana on MM - 01" src="https://user-images.githubusercontent.com/40488822/83680959-faaba900-a5e1-11ea-8c9b-cadd8c133d4d.png">

With kind regards,

@evroom

**Comment by SvenSommer** [comment]
Hey sorry for the late response.
Hey is this still an issue?

**Comment by evroom** [comment]
That was quite some time ago :-)
Would have to reconfigure my Pi for that, have something else running now.
If I do not answer before Sunday (14.02.2021), then forget about it.

**Comment by klaernie** [comment]
Saw this today. I think we'll close that issue.
